# Generated by Django 4.1.1 on 2022-09-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='note',
            field=models.CharField(max_length=50, verbose_name='Подпись'),
        ),
    ]
