# Generated by Django 4.1.1 on 2022-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='приватный'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='приватный'),
        ),
    ]
